version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-postgres}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-postgres}'
      POSTGRES_DB: '${POSTGRES_DB:-parqueen}'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '${DB_PORT:-5432}:5432'

  api:
    build:
      context: ./backend-parqueen
      dockerfile: Dockerfile
    container_name: nest_api
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: '${DB_PORT:-5432}'
      DATABASE_USER: '${POSTGRES_USER:-postgres}'
      DATABASE_PASSWORD: '${POSTGRES_PASSWORD:-postgres}'
      DATABASE_NAME: '${POSTGRES_DB:-parqueen}'
    command: sh -c "npx wait-on tcp:db:5432 && npm run start:prod"
    ports:
      - '${BACKEND_PORT:-3000}:3000'

#  frontend:
#    build:
#      context: ./frontend-parqueen
#      dockerfile: Dockerfile
#      args:
#        VITE_BACKEND_URL: localhost:${BACKEND_PORT:-3000}
#    container_name: vite_frontend
#    depends_on:
#      - api
#    environment:
#      VITE_BACKEND_URL: ${BACKEND_URL:-http://localhost:3000}
#    ports:
#      - '${FRONTEND_PORT:-80}:80'
volumes:
  pgdata: